name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-ci:

    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Download PHP_CodeSniffer phars
      run: |
        curl -sSLo phpcs.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        curl -sSLo phpcbf.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
        chmod +x phpcs.phar phpcbf.phar
        sudo mv phpcs.phar /usr/local/bin/phpcs
        sudo mv phpcbf.phar /usr/local/bin/phpcbf

    - name: Check code style with PHPCS
      run: |
        phpcs \
          --standard=PSR12 \
          --extensions=php \
          --ignore=vendor/ \
          .
    - name: Auto-fix code style with PHPCBF
      run: |
        phpcbf \
          --standard=PSR12 \
          --extensions=php \
          --ignore=vendor/ \
          .
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run PHPUnit
      run: vendor/bin/phpunit --colors=always --stop-on-failur
  
